- name: replace the policy as it is deprecated
  ansible.builtin.lineinfile:
    path: cockroach/files/cockroachdb-statefulset-secure.yaml
    search_string: 'apiVersion: policy/v1beta1'
    line: 'apiVersion: policy/v1'
